// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';

const CODE_REPO = 'https://github.com/openpreflight/openpreflight';
const SITE = 'https://docs.openpreflight.xyz';

// This repository is the source of truth for the documentation. Pages live
// under src/content/docs/, one directory per sidebar group. Every group is
// autogenerated, so adding or removing a page needs no change here — drop the
// markdown in the right directory and set `sidebar.order` in its frontmatter.
export default defineConfig({
  site: SITE,
  integrations: [
    starlight({
      title: 'openpreflight',
      description:
        'Self-hosted GitHub Check Runs CI for private repos. One Go binary, one SQLite file.',
      logo: {
        light: './src/assets/logo-light.svg',
        dark: './src/assets/logo-dark.svg',
        alt: 'openpreflight',
        replacesTitle: false,
      },
      favicon: '/favicon.svg',
      social: [{ icon: 'github', label: 'GitHub', href: CODE_REPO }],
      editLink: {
        baseUrl: 'https://github.com/openpreflight/docs/edit/main/',
      },
      customCss: ['./src/styles/global.css'],
      head: [
        {
          tag: 'link',
          attrs: { rel: 'icon', href: '/favicon.ico', sizes: 'any' },
        },
        {
          tag: 'link',
          attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32.png' },
        },
        {
          tag: 'link',
          attrs: { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: `${SITE}/og.png` },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:card', content: 'summary_large_image' },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:image', content: `${SITE}/og.png` },
        },
        {
          tag: 'meta',
          attrs: { name: 'theme-color', content: '#2f6f4f' },
        },
      ],
      sidebar: [
        { label: 'Start here', items: [{ autogenerate: { directory: 'start' } }] },
        { label: 'Setup', items: [{ autogenerate: { directory: 'setup' } }] },
        { label: 'Using it', items: [{ autogenerate: { directory: 'using' } }] },
        {
          label: 'Understanding it',
          items: [{ autogenerate: { directory: 'understanding' } }],
        },
        {
          label: 'Decisions',
          collapsed: true,
          items: [{ autogenerate: { directory: 'adr' } }],
        },
        { label: 'Contributing', items: [{ autogenerate: { directory: 'contributing' } }] },
      ],
      lastUpdated: true,
    }),
  ],
  vite: { plugins: [tailwindcss()] },
});
