// @ts-check
import { existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';

const CODE_REPO = 'https://github.com/openpreflight/openpreflight';
const SITE = 'https://docs.openpreflight.xyz';
const contentDir = fileURLToPath(new URL('./src/content/docs', import.meta.url));

/** @param {string} pathname */
function pageSource(pathname) {
  const trimmed = pathname.replace(/\/$/, '');
  const rel = trimmed === '' ? 'index' : trimmed.replace(/^\//, '');
  return ['md', 'mdx'].flatMap((ext) => [
    join(contentDir, `${rel}.${ext}`),
    join(contentDir, rel, `index.${ext}`),
  ]).find((candidate) => existsSync(candidate));
}

// This repository is the source of truth for the documentation. Pages live
// under src/content/docs/, one directory per sidebar group. Every group is
// autogenerated, so adding or removing a page needs no change here — drop the
// markdown in the right directory and set `sidebar.order` in its frontmatter.
export default defineConfig({
  site: SITE,
  // Every 2.0 URL still resolves. Kept indefinitely: they are in the
  // changelog, in the README and on the website.
  redirects: {
    '/start/quickstart/': '/getting-started/quickstart/',
    '/start/faq/': '/getting-started/faq/',
    '/start/comparison/': '/getting-started/comparison/',
    '/start/configuration/': '/configure/configuration/',
    '/setup/github-app/': '/configure/github-app/',
    '/setup/bindings/': '/configure/bindings/',
    '/setup/resolution/': '/configure/resolution/',
    '/setup/path-filters/': '/configure/path-filters/',
    '/setup/coolify/': '/deploy/coolify/',
    '/understanding/deployment/': '/deploy/deployment/',
    '/understanding/networking/': '/deploy/networking/',
    '/understanding/operations/': '/operate/operations/',
    '/using/troubleshooting/': '/operate/troubleshooting/',
    '/understanding/architecture/': '/reference/architecture/',
    '/understanding/security-model/': '/reference/security-model/',
    '/using/api/': '/reference/api/',
    '/using/pipelines/': '/use/pipelines/',
    '/using/runs/': '/use/runs/',
    '/using/logs/': '/use/logs/',
    '/adr/001-database/': '/reference/decisions/001-database/',
    '/adr/002-authentication/': '/reference/decisions/002-authentication/',
    '/adr/003-github-app/': '/reference/decisions/003-github-app/',
    '/adr/004-docker-executor/': '/reference/decisions/004-docker-executor/',
    '/adr/005-check-suite-gating/': '/reference/decisions/005-check-suite-gating/',
  },
  integrations: [
    sitemap({
      serialize(item) {
        const file = pageSource(new URL(item.url).pathname);
        if (file) item.lastmod = statSync(file).mtime.toISOString();
        return item;
      },
    }),
    starlight({
      title: 'openpreflight',
      description:
        'A small CI provider for private repos. One Go binary, one SQLite file: register a GitHub App, enable your repos, and get one Check Run per commit.',
      routeMiddleware: './src/routeData.ts',
      logo: {
        light: './src/assets/logo-light.svg',
        dark: './src/assets/logo-dark.svg',
        alt: 'openpreflight',
        replacesTitle: false,
      },
      favicon: '/favicon.svg',
      social: [{ icon: 'github', label: 'GitHub', href: CODE_REPO }],
      editLink: {
        baseUrl: 'https://github.com/openpreflight/docs/edit/main/',
      },
      customCss: ['./src/styles/global.css'],
      components: {
        Footer: './src/components/Footer.astro',
        PageFrame: './src/components/PageFrame.astro',
      },
      head: [
        {
          tag: 'link',
          attrs: { rel: 'icon', href: '/favicon.ico', sizes: 'any' },
        },
        {
          tag: 'link',
          attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32.png' },
        },
        {
          tag: 'link',
          attrs: { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
        },
        {
          tag: 'link',
          attrs: { rel: 'manifest', href: '/site.webmanifest' },
        },
        {
          tag: 'link',
          attrs: { rel: 'describedby', href: `${SITE}/llms.txt` },
        },
        {
          tag: 'meta',
          attrs: { name: 'apple-mobile-web-app-title', content: 'openpreflight' },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:card', content: 'summary_large_image' },
        },
        {
          tag: 'meta',
          attrs: { name: 'theme-color', content: '#2f6f4f' },
        },
      ],
      sidebar: [
        { label: 'Getting Started', items: [{ autogenerate: { directory: 'getting-started' } }] },
        { label: 'Deploy', items: [{ autogenerate: { directory: 'deploy' } }] },
        { label: 'Configure', items: [{ autogenerate: { directory: 'configure' } }] },
        { label: 'Use', items: [{ autogenerate: { directory: 'use' } }] },
        { label: 'Operate', items: [{ autogenerate: { directory: 'operate' } }] },
        {
          // Listed rather than autogenerated: an autogenerated nested directory
          // takes the directory name as its label, and 'decisions' reads wrong
          // next to the capitalised groups above.
          label: 'Reference',
          items: [
            'reference/architecture',
            'reference/security-model',
            'reference/api',
            {
              label: 'Decisions',
              collapsed: true,
              items: [{ autogenerate: { directory: 'reference/decisions' } }],
            },
          ],
        },
        { label: 'Contributing', items: [{ autogenerate: { directory: 'contributing' } }] },
      ],
      lastUpdated: true,
    }),
  ],
  vite: { plugins: [tailwindcss()] },
});
